### ISSUE TITLE
Should this issue have standard label set, and appear in clone-missing-repos.sh?

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-ios-vibtest-app#2]
I noticed this repo does not use the standard label set, nor does it clone when using clone-missing-repos.sh. I haven't checked whether there are other steps to set up this repo, but I wasn't sure this is necessary.  Is this repo intended to be short-lived, and not need all of the setup steps?

**Comment by jessegreenberg** [comment]
This repo is intended to be short lived (on the order of 6 months). And it did not seem important for developers to have this cloned. But I will go through the checklist and make sure important parts are done.

**Comment by jessegreenberg** [comment]
## Steps to create a new simulation repo

At https://github.com/phetsims:
- [x] Press the "New" button. 
- [x] ~~Set the Description field to `"{{TITLE}}" is an educational simulation in HTML5, by PhET Interactive Simulations.`~~ 
- [x] Set visibility to "Public". 
- [x] DO NOT check the "Initialize this repository with a README" checkbox. 
- [x] Leave "Add .gitignore" set to "None"
- [x] Leave "Add a license" set to "None". 

In your working copy of perennial repo:
- [ ] ~~Run `grunt create-sim --repo={{REPO}} --author="{{AUTHOR}}" --title="{{TITLE}}"` to create the file structure and skeleton code for the sim.~~

In your working copy of the sim repo: 
- [x] `git init`
- [ ] ~~`git add * .gitignore`~~ - unsure about gitignore for a swift app, leaving for the moment
- [x] `git commit -m "Initial commit"`
- [x] `git remote add origin https://github.com/phetsims/{{REPO}}.git`
- [x] `git push -u origin master`

In your working copy of perennial repo:
- [ ] ~~Add the new repo to `perennial/data/active-repos`. Run `clone-missing-repos.sh` to check your change, commit and push. After a few minutes, an automated process should update the other files under perennial/data/. Pull perennial so you can find the sim in phetmarks.~~

At https://github.com/phetsims/{{REPO}}:
- [x] Go to Settings => Collaborators and Teams, add the teams used in another public sims (currently Design, Development, and Quality Assurance) with "Write" permissions.
- [ ] ~~Create a Master Checklist issue using template [sim_new_checklist.md](https://github.com/phetsims/phet-info/blob/master/checklists/sim_new_checklist.md). Use "{{TITLE}} Master Checklist" as the issue name. Assign to @ariel-phet.~~

Other:
- [ ] ~~Navigate to phettest.colorado.edu and click the "Refresh Perennial" button. If you're off campus, [CU's VPN service](https://oit.colorado.edu/services/network-internet-services/vpn) is required to access phettest.colorado.edu.~~
- [x] Apply GitHub labels. See [github-labels/README.md](https://github.com/phetsims/phet-info/blob/master/github-labels/README.md).
- [ ] ~~Notify Slack channel dev-public that the repo has been created. E.g. "I just added a new repository, {{REPO}}. Please pull perennial and run `clone-missing-repos.sh` at your convenience."~~
- [ ] ~~If using IDEA/Webstorm (pre-2018), add the git source root for the repository.~~
- [ ] ~~Follow any remaining "Implementation" tasks in the Master Checklist issue that you created above.~~
- [ ] ~~If applicable, add any needed dependencies to `phetLibs` in package.json. If you change package.json, run `grunt update`.~~
- [ ] ~~Add the sim to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md).~~

## Steps to create a different type of repo

At https://github.com/phetsims:
- [x] Press the "New" button. 
- [x] Fill in the Description field.  (Ask other developers if you need suggestions.) 
- [x] Decide on visibility. (Ask other developers if you're not sure.) 
- [x] Typically do not select options that would initialize the repo by creating files (README, .gitignore, LICENSE).

In your working copy of the sim repo:
- [x] Create the file structure locally. It's best to start (currently) by copying from a similar repository (but without the `.git` directory). Make sure to keep `.gitignore`, etc.
- [x] `git init`
- [x] `git add * .gitignore`
- [x] `git commit -m "Initial commit"`
- [x] `git remote add origin https://github.com/phetsims/{{REPO}}.git`
- [x] `git push -u origin master`

At https://github.com/phetsims/{{REPO}}:
- [x] Go to Settings => Collaborators and Teams, add the teams used in another public sims (currently Design, Development, and Quality Assurance) with "Write" permissions. _NOTE: If the repo is private, it is REQUIRED to add the Machine User collaborator (so automated processes can clone/pull the repo). CT will break otherwise.

~~In your working copy of perennial repo:~~
- [ ] ~~If applicable: Add the new repo to `perennial/data/active-repos`. Run `clone-missing-repos.sh` to check your change, commit and push. After a few minutes, an automated process should update the other files under perennial/data/. Pull perennial so you can find the sim in phetmarks.~~

If this repo is a common code dependency for all sims:
- [ ] ~~Add it to the list of `clone` commands in [phet-development-overview.md](https://github.com/phetsims/phet-info/blob/master/doc/phet-development-overview.md)~~
- [ ] ~~Update all sim published README files (because the "Quick Start" section has these git clone commands too).~~

Other:
- [x] Notify Slack channel dev-public that the repo has been created. E.g. "I just added a new repository, {{REPO}}. Please pull perennial and run `clone-missing-repos.sh` at your convenience."
- [ ] ~~Apply GitHub labels. See [github-labels/README.md](https://github.com/phetsims/phet-info/blob/master/github-labels/README.md).~~
- [ ] ~~If using IDEA/Webstorm (pre-2018), add the git source root for the repository.~~

**Comment by jessegreenberg** [comment]
I asked over slack if others would like to have this in active-repos, given the nature of this repo. 

EDIT: People on slack said "I am not sure one way or the other." Im not going to add to active-repos, I don't feel that others should need to clone this unless they have interest.

**Comment by jessegreenberg** [comment]
Standard label set was added.

I went through the checklist and checked items off or crossed them out if they don't apply to this repo. Closing.
